export const CLOSE_SEARCH_BAR = "CLOSE_SEARCH_BAR";
export const OPEN_SEARCH_BAR = "OPEN_SEARCH_BAR";
export const GET_TODAYS_WEATHER = "GET_TODAYS_WEATHER";
export const GET_DAILY_WEATHER = "GET_DAILY_WEATHER";
